-- Phase 3: Seed exercise library (~80 exercises across 8 categories)
-- Only runs once via schema_migrations tracking in migrate.ts

INSERT INTO exercises (name, category, exercise_type, muscles_primary, muscles_secondary, is_custom) VALUES
-- Chest
('Barbell Bench Press',        'Chest',      'weight',      '["Chest"]',                    '["Shoulders","Triceps"]',  0),
('Incline Barbell Bench Press','Chest',      'weight',      '["Chest"]',                    '["Shoulders","Triceps"]',  0),
('Decline Barbell Bench Press','Chest',      'weight',      '["Chest"]',                    '["Triceps"]',              0),
('Dumbbell Bench Press',       'Chest',      'weight',      '["Chest"]',                    '["Shoulders","Triceps"]',  0),
('Dumbbell Flyes',             'Chest',      'weight',      '["Chest"]',                    '["Shoulders"]',            0),
('Cable Crossover',            'Chest',      'weight',      '["Chest"]',                    '["Shoulders"]',            0),
('Push-Up',                    'Chest',      'bodyweight',  '["Chest"]',                    '["Shoulders","Triceps"]',  0),
('Chest Dip',                  'Chest',      'bodyweight',  '["Chest"]',                    '["Triceps","Shoulders"]',  0),
-- Back
('Pull-Up',                    'Back',       'bodyweight',  '["Back","Biceps"]',             '["Core"]',                 0),
('Chin-Up',                    'Back',       'bodyweight',  '["Back","Biceps"]',             '[]',                       0),
('Barbell Row',                'Back',       'weight',      '["Back"]',                     '["Biceps","Core"]',        0),
('Dumbbell Row',               'Back',       'weight',      '["Back"]',                     '["Biceps"]',               0),
('Lat Pulldown',               'Back',       'weight',      '["Back"]',                     '["Biceps"]',               0),
('Seated Cable Row',           'Back',       'weight',      '["Back"]',                     '["Biceps"]',               0),
('T-Bar Row',                  'Back',       'weight',      '["Back"]',                     '["Biceps"]',               0),
('Deadlift',                   'Back',       'weight',      '["Back","Glutes","Hamstrings"]','["Core","Forearms"]',      0),
('Romanian Deadlift',          'Back',       'weight',      '["Hamstrings","Glutes"]',       '["Lower Back"]',           0),
('Face Pull',                  'Back',       'weight',      '["Shoulders","Back"]',          '["Biceps"]',               0),
-- Shoulders
('Overhead Press',             'Shoulders',  'weight',      '["Shoulders"]',                '["Triceps","Core"]',       0),
('Dumbbell Shoulder Press',    'Shoulders',  'weight',      '["Shoulders"]',                '["Triceps"]',              0),
('Lateral Raise',              'Shoulders',  'weight',      '["Shoulders"]',                '[]',                       0),
('Front Raise',                'Shoulders',  'weight',      '["Shoulders"]',                '[]',                       0),
('Rear Delt Fly',              'Shoulders',  'weight',      '["Shoulders","Back"]',          '[]',                       0),
('Arnold Press',               'Shoulders',  'weight',      '["Shoulders"]',                '["Triceps"]',              0),
('Upright Row',                'Shoulders',  'weight',      '["Shoulders","Back"]',          '["Biceps"]',               0),
-- Arms
('Barbell Curl',               'Arms',       'weight',      '["Biceps"]',                   '["Forearms"]',             0),
('Dumbbell Curl',              'Arms',       'weight',      '["Biceps"]',                   '["Forearms"]',             0),
('Hammer Curl',                'Arms',       'weight',      '["Biceps","Forearms"]',         '[]',                       0),
('Preacher Curl',              'Arms',       'weight',      '["Biceps"]',                   '[]',                       0),
('Cable Curl',                 'Arms',       'weight',      '["Biceps"]',                   '[]',                       0),
('Concentration Curl',         'Arms',       'weight',      '["Biceps"]',                   '[]',                       0),
('Tricep Pushdown',            'Arms',       'weight',      '["Triceps"]',                  '[]',                       0),
('Overhead Tricep Extension',  'Arms',       'weight',      '["Triceps"]',                  '[]',                       0),
('Skull Crusher',              'Arms',       'weight',      '["Triceps"]',                  '[]',                       0),
('Close-Grip Bench Press',     'Arms',       'weight',      '["Triceps","Chest"]',           '[]',                       0),
('Tricep Dip',                 'Arms',       'bodyweight',  '["Triceps"]',                  '["Chest","Shoulders"]',    0),
('Diamond Push-Up',            'Arms',       'bodyweight',  '["Triceps","Chest"]',           '[]',                       0),
-- Legs
('Back Squat',                 'Legs',       'weight',      '["Quads","Glutes"]',            '["Hamstrings","Core"]',    0),
('Front Squat',                'Legs',       'weight',      '["Quads"]',                    '["Glutes","Core"]',        0),
('Goblet Squat',               'Legs',       'weight',      '["Quads","Glutes"]',            '["Core"]',                 0),
('Leg Press',                  'Legs',       'weight',      '["Quads","Glutes"]',            '["Hamstrings"]',           0),
('Hack Squat',                 'Legs',       'weight',      '["Quads"]',                    '["Glutes","Hamstrings"]',  0),
('Leg Curl',                   'Legs',       'weight',      '["Hamstrings"]',                '[]',                       0),
('Leg Extension',              'Legs',       'weight',      '["Quads"]',                    '[]',                       0),
('Standing Calf Raise',        'Legs',       'weight',      '["Calves"]',                   '[]',                       0),
('Seated Calf Raise',          'Legs',       'weight',      '["Calves"]',                   '[]',                       0),
('Lunge',                      'Legs',       'weight',      '["Quads","Glutes"]',            '["Hamstrings"]',           0),
('Bulgarian Split Squat',      'Legs',       'weight',      '["Quads","Glutes"]',            '["Hamstrings"]',           0),
('Hip Thrust',                 'Legs',       'weight',      '["Glutes"]',                   '["Hamstrings"]',           0),
('Sumo Deadlift',              'Legs',       'weight',      '["Glutes","Hamstrings","Back"]','["Quads"]',                0),
-- Core
('Plank',                      'Core',       'duration',    '["Core"]',                     '[]',                       0),
('Crunch',                     'Core',       'bodyweight',  '["Core"]',                     '[]',                       0),
('Sit-Up',                     'Core',       'bodyweight',  '["Core"]',                     '[]',                       0),
('Leg Raise',                  'Core',       'bodyweight',  '["Core"]',                     '[]',                       0),
('Russian Twist',              'Core',       'bodyweight',  '["Core"]',                     '[]',                       0),
('Mountain Climber',           'Core',       'bodyweight',  '["Core"]',                     '["Shoulders"]',            0),
('Ab Wheel Rollout',           'Core',       'bodyweight',  '["Core"]',                     '["Shoulders","Back"]',     0),
('Cable Crunch',               'Core',       'weight',      '["Core"]',                     '[]',                       0),
('Hanging Leg Raise',          'Core',       'bodyweight',  '["Core"]',                     '[]',                       0),
('Dead Bug',                   'Core',       'bodyweight',  '["Core"]',                     '[]',                       0),
-- Cardio
('Running',                    'Cardio',     'cardio',      '["Legs"]',                     '["Core"]',                 0),
('Treadmill',                  'Cardio',     'cardio',      '["Legs"]',                     '[]',                       0),
('Cycling',                    'Cardio',     'cardio',      '["Legs"]',                     '[]',                       0),
('Rowing Machine',             'Cardio',     'cardio',      '["Back","Legs"]',               '["Core","Arms"]',          0),
('Elliptical',                 'Cardio',     'cardio',      '["Legs"]',                     '["Core"]',                 0),
('Jump Rope',                  'Cardio',     'cardio',      '["Calves","Legs"]',             '["Shoulders","Core"]',     0),
('Stair Climber',              'Cardio',     'cardio',      '["Legs","Glutes"]',             '[]',                       0),
('Swimming',                   'Cardio',     'cardio',      '["Full Body"]',                '[]',                       0),
('HIIT',                       'Cardio',     'cardio',      '["Full Body"]',                '[]',                       0),
('Walking',                    'Cardio',     'cardio',      '["Legs"]',                     '[]',                       0),
-- Full Body
('Burpee',                     'Full Body',  'bodyweight',  '["Full Body"]',                '[]',                       0),
('Clean and Jerk',             'Full Body',  'weight',      '["Full Body"]',                '[]',                       0),
('Power Clean',                'Full Body',  'weight',      '["Full Body"]',                '[]',                       0),
('Kettlebell Swing',           'Full Body',  'weight',      '["Glutes","Hamstrings"]',       '["Core","Shoulders"]',     0),
('Box Jump',                   'Full Body',  'bodyweight',  '["Legs","Glutes"]',             '[]',                       0),
('Thruster',                   'Full Body',  'weight',      '["Full Body"]',                '[]',                       0),
('Turkish Get-Up',             'Full Body',  'weight',      '["Full Body"]',                '["Core"]',                 0),
('Battle Ropes',               'Full Body',  'duration',    '["Shoulders","Core"]',          '["Arms"]',                 0),
('Farmer Walk',                'Full Body',  'weight',      '["Forearms","Core"]',           '["Legs","Back"]',          0),
('Sled Push',                  'Full Body',  'weight',      '["Legs","Full Body"]',          '[]',                       0);
