CREATE TABLE IF NOT EXISTS custom_goals (
  id           INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id      INT UNSIGNED NOT NULL,
  name         VARCHAR(100) NOT NULL,
  category     ENUM('body','nutrition','exercise') NOT NULL,
  metric_type  ENUM(
    'exercise_max_weight',
    'exercise_max_reps',
    'exercise_session_volume',
    'exercise_weekly_volume',
    'exercise_session_reps',
    'exercise_weekly_reps',
    'exercise_session_steps',
    'exercise_weekly_steps',
    'exercise_session_distance',
    'exercise_weekly_distance',
    'exercise_session_duration',
    'exercise_weekly_duration',
    'exercise_weekly_sessions',
    'daily_steps_avg',
    'weekly_steps_total',
    'body_measurement',
    'nutrition_daily_avg'
  ) NOT NULL,
  source_type  ENUM('exercise','routine','measurement','nutrition','steps') NOT NULL,
  source_id    INT UNSIGNED NULL,
  source_key   VARCHAR(50)  NULL,
  target_value DECIMAL(10,2) NOT NULL,
  unit         VARCHAR(20)  NOT NULL,
  target_date  DATE         NULL,
  sort_order   INT          NOT NULL DEFAULT 0,
  created_at   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_user_category (user_id, category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
