server {
    listen 80;
    root /usr/share/nginx/html;

    location /pulse/ {
        index index.html;
        try_files $uri $uri/ /pulse/index.html;
    }

    location = / {
        return 301 /pulse/;
    }
}
