/**
 * Generates apps/web/src/index.css from the PALETTES source of truth.
 * Run with: npm run generate-css --workspace=packages/theme
 */
import * as fs from 'fs';
import * as path from 'path';
import { PALETTES } from '../src/index';

type PaletteName = keyof typeof PALETTES;

/** Convert a hex color (#RRGGBB) to space-separated RGB channels for Tailwind opacity support */
function hexToRgbChannels(hex: string): string {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return `${r} ${g} ${b}`;
}

function buildThemeBlock(name: PaletteName, selector: string): string {
  const p = PALETTES[name];
  const lines = [
    `${selector} {`,
    `  --color-bg:     ${hexToRgbChannels(p.bg)};`,
    `  --color-card:   ${hexToRgbChannels(p.card)};`,
    `  --color-accent: ${hexToRgbChannels(p.accent)};`,
    `  --color-border: ${hexToRgbChannels(p.border)};`,
    `  --color-muted:  ${hexToRgbChannels(p.muted)};`,
    `  --color-text:   ${hexToRgbChannels(p.text)};`,
    `}`,
  ];
  return lines.join('\n');
}

const themeBlocks = (Object.keys(PALETTES) as PaletteName[]).map((name, i) => {
  const selector = i === 0
    ? `:root,\n[data-theme="${name}"]`
    : `[data-theme="${name}"]`;
  return buildThemeBlock(name, selector);
}).join('\n\n');

const GENERATED_START = '/* ── Theme variables';
const LAYER_BASE = '\n@layer base';

const generatedSection =
`/* ── Theme variables ──────────────────────────────────────── */
/* Generated by packages/theme/scripts/generateCssVars.ts     */
/* To update colors, edit packages/theme/src/index.ts         */
/* and run: npm run generate-css --workspace=packages/theme   */
/* Values are R G B channels (no commas) for Tailwind opacity support */
${themeBlocks}`;

const outPath = path.resolve(__dirname, '../../../apps/web/src/index.css');
const existing = fs.readFileSync(outPath, 'utf8');

const startIdx = existing.indexOf(GENERATED_START);
const layerIdx = existing.indexOf(LAYER_BASE);
if (startIdx === -1 || layerIdx === -1) {
  throw new Error('Could not find theme variable markers in index.css');
}

const replaced = existing.slice(0, startIdx) + generatedSection + '\n' + existing.slice(layerIdx);

fs.writeFileSync(outPath, replaced, 'utf8');
console.log(`Written: ${outPath}`);
