/**
 * Generates apps/web/src/index.css from the PALETTES source of truth.
 * Run with: npm run generate-css --workspace=packages/theme
 */
import * as fs from 'fs';
import * as path from 'path';
import { PALETTES } from '../src/index';

type PaletteName = keyof typeof PALETTES;

/** Convert a hex color (#RRGGBB) to space-separated RGB channels for Tailwind opacity support */
function hexToRgbChannels(hex: string): string {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return `${r} ${g} ${b}`;
}

function buildThemeBlock(name: PaletteName, selector: string): string {
  const p = PALETTES[name];
  const lines = [
    `${selector} {`,
    `  --color-bg:     ${hexToRgbChannels(p.bg)};`,
    `  --color-card:   ${hexToRgbChannels(p.card)};`,
    `  --color-accent: ${hexToRgbChannels(p.accent)};`,
    `  --color-border: ${hexToRgbChannels(p.border)};`,
    `  --color-muted:  ${hexToRgbChannels(p.muted)};`,
    `}`,
  ];
  return lines.join('\n');
}

const css = `@tailwind base;
@tailwind components;
@tailwind utilities;

/* ── Theme variables ──────────────────────────────────────── */
/* Generated by packages/theme/scripts/generateCssVars.ts     */
/* To update colors, edit packages/theme/src/index.ts         */
/* and run: npm run generate-css --workspace=packages/theme   */
/* Values are R G B channels (no commas) for Tailwind opacity support */
${buildThemeBlock('blue', ':root,\n[data-theme="blue"]')}

${buildThemeBlock('slate', '[data-theme="slate"]')}

${buildThemeBlock('sand', '[data-theme="sand"]')}

@layer base {
  html { background-color: rgb(var(--color-bg)); color: white; }
}
`;

const outPath = path.resolve(__dirname, '../../../apps/web/src/index.css');
fs.writeFileSync(outPath, css, 'utf8');
console.log(`Written: ${outPath}`);
